language: python
python:
  - "2.7"
install:
  - pip install .
  - pip install coveralls
script:
  nosetests --with-coverage --cover-package=plugit --cover-package=plugit_proxy --cover-package=plugIt tests
after_success:
  coveralls
